name       : virtualenv
version    : 15.1.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-15.1.0.tar.gz : 02f8102c2436bb03b3ee6dede1919d1dac8a427541652e5ec95171ec8adbc93a
license    : MIT
component  : programming.python
summary    : Tool to create isolated 'virtual' python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier
    management of versions and dependencies in Python applications.
builddeps  :
    - python-mock
    - python-pytest
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test -v
    popd
    pushd $PKG_BUILD_DIR/py3build
        py.test3 -v
    popd

