name       : virtualenv
version    : 20.10.0
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-20.10.0.tar.gz : 576d05b46eace16a9c348085f7d0dc8ef28713a2cabaa1cf0aea41e8f12c9218
license    : MIT
component  : programming.python
summary    : Tool to create isolated 'virtual' python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier management of versions and dependencies in Python applications.
networking : yes
builddeps  :
    - python-backports.entry_points_selectable
    - python-distlib
    - python-filelock
    - python-flaky # check
    - python-platformdirs
    - python-pytest-mock # check
    - python-setuptools-scm
rundeps    :
    - python-backports.entry_points_selectable
    - python-distlib
    - python-filelock
    - python-platformdirs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not (test_periodic_update or test_build_c_ext)'
