name       : virtualenv
version    : 15.0.3
release    : 5
source     :
    - https://pypi.python.org/packages/8b/2c/c0d3e47709d0458816167002e1aa3d64d03bdeb2a9d57c5bd18448fd24cd/virtualenv-15.0.3.tar.gz : 6d9c760d3fc5fa0894b0f99b9de82a4647e1164f0b700a7f99055034bf548b1d
license    : MIT
component  : programming.tools
summary    : Tool to create isolated Python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier
    management of versions and dependencies in Python applications.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
