name       : virtualenv
version    : 20.16.6
release    : 18
source     :
    - https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-20.16.6.tar.gz : 530b850b523c6449406dfba859d6345e48ef19b8439606c5d74d7d3c9e14d76e
homepage   : https://virtualenv.pypa.io/
license    : MIT
component  : programming.python
summary    : Tool to create isolated 'virtual' python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier management of versions and dependencies in Python applications.
networking : yes
builddeps  :
    - python-distlib
    - python-filelock
    - python-flaky # check
    - python-platformdirs
    - python-pytest-mock # check
    - python-setuptools-scm
rundeps    :
    - python-distlib
    - python-filelock
    - python-platformdirs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not (test_periodic_update or test_build_c_ext or test_get_wheel_download_cached)'
