name       : virtualenv
version    : 20.14.1
release    : 16
source     :
    - https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-20.14.1.tar.gz : ef589a79795589aada0c1c5b319486797c03b67ac3984c48c669c0e4f50df3a5
license    : MIT
component  : programming.python
summary    : Tool to create isolated 'virtual' python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier management of versions and dependencies in Python applications.
networking : yes
builddeps  :
    - python-backports.entry_points_selectable
    - python-distlib
    - python-filelock
    - python-flaky # check
    - python-platformdirs
    - python-pytest-mock # check
    - python-setuptools-scm
rundeps    :
    - python-backports.entry_points_selectable
    - python-distlib
    - python-filelock
    - python-platformdirs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not (test_periodic_update or test_build_c_ext or test_get_wheel_download_cached)'
