name       : virtualenv
version    : 16.1.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz : f899fafcd92e1150f40c8215328be38ff24b519cd95357fa6e78e006c7638208
license    : MIT
component  : programming.python
summary    : Tool to create isolated 'virtual' python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier management of versions and dependencies in Python applications.
builddeps  :
    - python-mock
    - python-pytest
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not test_always_copy_option'
