name       : virtualenv
version    : 20.7.2
release    : 14
source     :
    - https://files.pythonhosted.org/packages/source/v/virtualenv/virtualenv-20.7.2.tar.gz : 9ef4e8ee4710826e98ff3075c9a4739e2cb1040de6a2a8d35db0055840dc96a0
license    : MIT
component  : programming.python
summary    : Tool to create isolated 'virtual' python environments
description: |
    virtualenv is a tool to create isolated python environments, allowing for easier management of versions and dependencies in Python applications.
networking : yes
builddeps  :
    - python-backports.entry_points_selectable
    - python-distlib
    - python-filelock
    - python-flaky # check
    - python-platformdirs
    - python-pytest-mock # check
    - python-setuptools-scm
rundeps    :
    - python-backports.entry_points_selectable
    - python-distlib
    - python-filelock
    - python-platformdirs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not (test_periodic_update or test_build_c_ext)'
